# Generated by Django 5.2.6 on 2025-09-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('librarian', 'Librarian'), ('customer', 'Customer'), ('admin', 'Admin')], default='customer', max_length=10),
        ),
    ]
